### ISSUE TITLE
Placing bags of bread on the floor can cause a trap

### ISSUE THREAD

**Issue by mixxit** [mixxit/solinia3-core#377]
```
[05:22:54] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: TRAP
        at net.minecraft.server.v1_14_R1.ItemStack.checkEmpty(ItemStack.java:82) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.ItemStack.setCount(ItemStack.java:851) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.ItemStack.add(ItemStack.java:855) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.ItemStack.subtract(ItemStack.java:859) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:64) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.ItemBlock.a(ItemBlock.java:24) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:157) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:472) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]```

**Comment by mixxit** [comment]
reported by RockStarZane

**Comment by mixxit** [comment]
Confirmed locally
