### ISSUE TITLE
Remove Spell 

### ISSUE THREAD

**Issue by mixxit** [mixxit/solinia3-core#512]
`] [Server thread/WARN]: java.lang.NullPointerException
[07:51:13] [Server thread/WARN]:        at com.solinia.solinia.Models.SoliniaEntitySpells.removeSpell(SoliniaEntitySpells.java:592)
[07:51:13] [Server thread/WARN]:        at com.solinia.solinia.Models.SoliniaEntitySpells.removeAllSpells(SoliniaEntitySpells.java:674)
[07:51:13] [Server thread/WARN]:        at com.solinia.solinia.Managers.EntityManager.removeSpellEffects(EntityManager.java:532)
[07:51:13] [Server thread/WARN]:        at com.solinia.solinia.Managers.EntityManager.spellTick(EntityManager.java:507)
[07:51:13] [Server thread/WARN]:        at com.solinia.solinia.Managers.CoreState.spellTick(CoreState.java:693)
[07:51:13] [Server thread/WARN]:        at com.solinia.solinia.Timers.SpellTickTimer.run(SpellTickTimer.java:20)
[07:51:13] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[07:51:13] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[07:51:13] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022)
[07:51:13] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
[07:51:13] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
[07:51:13] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
[07:51:13] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by mixxit** [comment]
Fixed in a994ad03c2ebfa0c28ca1b2348ac18475ba7dcf9
